version: '3.8'

services:
  yt-dlp-web:
    build: .
    container_name: yt-dlp-web-v2
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 下载目录
      - ./downloads:/app/downloads
      # 配置文件
      - ./config.yml:/app/config.yml:ro
      # 日志目录
      - ./logs:/app/logs
      # 数据库持久化
      - ./data:/app/data
    environment:
      # 基础配置
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      
      # 数据库配置
      - DATABASE_URL=sqlite:///data/app.db
      
      # 下载配置
      - DOWNLOAD_DIR=/app/downloads
      - MAX_CONCURRENT=3
      
      # Telegram配置 (可选)
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID:-}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH:-}
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

# 可选：添加反向代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: yt-dlp-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - yt-dlp-web

volumes:
  downloads:
  logs:
  data:
